// Code generated by command: go run gen.go -out atomic_amd64.s -stubs atomic_amd64.go. DO NOT EDIT.

package atomics

func AddInt8(addr *int8, a0 int8)

func AddUint8(addr *uint8, a0 uint8)

func AddInt16(addr *int16, a0 int16)

func AddUint16(addr *uint16, a0 uint16)

func AddInt32(addr *int32, a0 int32)

func AddUint32(addr *uint32, a0 uint32)

func AddInt64(addr *int64, a0 int64)

func AddUint64(addr *uint64, a0 uint64)

func AddInt(addr *int, a0 int)

func AddUint(addr *uint, a0 uint)

func AddUintptr(addr *uintptr, a0 uintptr)

func AddWithCarryInt8(addr *int8, a0 int8)

func AddWithCarryUint8(addr *uint8, a0 uint8)

func AddWithCarryInt16(addr *int16, a0 int16)

func AddWithCarryUint16(addr *uint16, a0 uint16)

func AddWithCarryInt32(addr *int32, a0 int32)

func AddWithCarryUint32(addr *uint32, a0 uint32)

func AddWithCarryInt64(addr *int64, a0 int64)

func AddWithCarryUint64(addr *uint64, a0 uint64)

func AddWithCarryInt(addr *int, a0 int)

func AddWithCarryUint(addr *uint, a0 uint)

func AddWithCarryUintptr(addr *uintptr, a0 uintptr)

func AndInt8(addr *int8, a0 int8)

func AndUint8(addr *uint8, a0 uint8)

func AndInt16(addr *int16, a0 int16)

func AndUint16(addr *uint16, a0 uint16)

func AndInt32(addr *int32, a0 int32)

func AndUint32(addr *uint32, a0 uint32)

func AndInt64(addr *int64, a0 int64)

func AndUint64(addr *uint64, a0 uint64)

func AndInt(addr *int, a0 int)

func AndUint(addr *uint, a0 uint)

func AndUintptr(addr *uintptr, a0 uintptr)

func BitTestAndComplementInt16(addr *int16, a0 int16) int16

func BitTestAndComplementUint16(addr *uint16, a0 uint16) uint16

func BitTestAndComplementInt32(addr *int32, a0 int32) int32

func BitTestAndComplementUint32(addr *uint32, a0 uint32) uint32

func BitTestAndComplementInt64(addr *int64, a0 int64) int64

func BitTestAndComplementUint64(addr *uint64, a0 uint64) uint64

func BitTestAndComplementInt(addr *int, a0 int) int

func BitTestAndComplementUint(addr *uint, a0 uint) uint

func BitTestAndComplementUintptr(addr *uintptr, a0 uintptr) uintptr

func BitTestAndResetInt16(addr *int16, a0 int16) int16

func BitTestAndResetUint16(addr *uint16, a0 uint16) uint16

func BitTestAndResetInt32(addr *int32, a0 int32) int32

func BitTestAndResetUint32(addr *uint32, a0 uint32) uint32

func BitTestAndResetInt64(addr *int64, a0 int64) int64

func BitTestAndResetUint64(addr *uint64, a0 uint64) uint64

func BitTestAndResetInt(addr *int, a0 int) int

func BitTestAndResetUint(addr *uint, a0 uint) uint

func BitTestAndResetUintptr(addr *uintptr, a0 uintptr) uintptr

func BitTestAndSetInt16(addr *int16, a0 int16) int16

func BitTestAndSetUint16(addr *uint16, a0 uint16) uint16

func BitTestAndSetInt32(addr *int32, a0 int32) int32

func BitTestAndSetUint32(addr *uint32, a0 uint32) uint32

func BitTestAndSetInt64(addr *int64, a0 int64) int64

func BitTestAndSetUint64(addr *uint64, a0 uint64) uint64

func BitTestAndSetInt(addr *int, a0 int) int

func BitTestAndSetUint(addr *uint, a0 uint) uint

func BitTestAndSetUintptr(addr *uintptr, a0 uintptr) uintptr

func CompareAndSwapInt8(addr *int8, a0 int8, a1 int8) int8

func CompareAndSwapUint8(addr *uint8, a0 uint8, a1 uint8) uint8

func CompareAndSwapInt16(addr *int16, a0 int16, a1 int16) int16

func CompareAndSwapUint16(addr *uint16, a0 uint16, a1 uint16) uint16

func CompareAndSwapInt32(addr *int32, a0 int32, a1 int32) int32

func CompareAndSwapUint32(addr *uint32, a0 uint32, a1 uint32) uint32

func CompareAndSwapInt64(addr *int64, a0 int64, a1 int64) int64

func CompareAndSwapUint64(addr *uint64, a0 uint64, a1 uint64) uint64

func CompareAndSwapInt(addr *int, a0 int, a1 int) int

func CompareAndSwapUint(addr *uint, a0 uint, a1 uint) uint

func CompareAndSwapUintptr(addr *uintptr, a0 uintptr, a1 uintptr) uintptr

func CompareAndSwap2xInt64(addr *int64, a0 int64, a1 int64, a2 int64, a3 int64) (int64, int64)

func CompareAndSwap2xUint64(addr *uint64, a0 uint64, a1 uint64, a2 uint64, a3 uint64) (uint64, uint64)

func CompareAndSwap2xInt(addr *int, a0 int, a1 int, a2 int, a3 int) (int, int)

func CompareAndSwap2xUint(addr *uint, a0 uint, a1 uint, a2 uint, a3 uint) (uint, uint)

func CompareAndSwap2xUintptr(addr *uintptr, a0 uintptr, a1 uintptr, a2 uintptr, a3 uintptr) (uintptr, uintptr)

func DecrementInt8(addr *int8)

func DecrementUint8(addr *uint8)

func DecrementInt16(addr *int16)

func DecrementUint16(addr *uint16)

func DecrementInt32(addr *int32)

func DecrementUint32(addr *uint32)

func DecrementInt64(addr *int64)

func DecrementUint64(addr *uint64)

func DecrementInt(addr *int)

func DecrementUint(addr *uint)

func DecrementUintptr(addr *uintptr)

func DecrementAndCheckZeroInt8(addr *int8) int8

func DecrementAndCheckZeroUint8(addr *uint8) uint8

func DecrementAndCheckZeroInt16(addr *int16) int16

func DecrementAndCheckZeroUint16(addr *uint16) uint16

func DecrementAndCheckZeroInt32(addr *int32) int32

func DecrementAndCheckZeroUint32(addr *uint32) uint32

func DecrementAndCheckZeroInt64(addr *int64) int64

func DecrementAndCheckZeroUint64(addr *uint64) uint64

func DecrementAndCheckZeroInt(addr *int) int

func DecrementAndCheckZeroUint(addr *uint) uint

func DecrementAndCheckZeroUintptr(addr *uintptr) uintptr

func IncrementInt8(addr *int8)

func IncrementUint8(addr *uint8)

func IncrementInt16(addr *int16)

func IncrementUint16(addr *uint16)

func IncrementInt32(addr *int32)

func IncrementUint32(addr *uint32)

func IncrementInt64(addr *int64)

func IncrementUint64(addr *uint64)

func IncrementInt(addr *int)

func IncrementUint(addr *uint)

func IncrementUintptr(addr *uintptr)

func IncrementAndCheckZeroInt8(addr *int8) int8

func IncrementAndCheckZeroUint8(addr *uint8) uint8

func IncrementAndCheckZeroInt16(addr *int16) int16

func IncrementAndCheckZeroUint16(addr *uint16) uint16

func IncrementAndCheckZeroInt32(addr *int32) int32

func IncrementAndCheckZeroUint32(addr *uint32) uint32

func IncrementAndCheckZeroInt64(addr *int64) int64

func IncrementAndCheckZeroUint64(addr *uint64) uint64

func IncrementAndCheckZeroInt(addr *int) int

func IncrementAndCheckZeroUint(addr *uint) uint

func IncrementAndCheckZeroUintptr(addr *uintptr) uintptr

func NegateInt8(addr *int8)

func NegateUint8(addr *uint8)

func NegateInt16(addr *int16)

func NegateUint16(addr *uint16)

func NegateInt32(addr *int32)

func NegateUint32(addr *uint32)

func NegateInt64(addr *int64)

func NegateUint64(addr *uint64)

func NegateInt(addr *int)

func NegateUint(addr *uint)

func NegateUintptr(addr *uintptr)

func NotInt8(addr *int8)

func NotUint8(addr *uint8)

func NotInt16(addr *int16)

func NotUint16(addr *uint16)

func NotInt32(addr *int32)

func NotUint32(addr *uint32)

func NotInt64(addr *int64)

func NotUint64(addr *uint64)

func NotInt(addr *int)

func NotUint(addr *uint)

func NotUintptr(addr *uintptr)

func OrInt8(addr *int8, a0 int8)

func OrUint8(addr *uint8, a0 uint8)

func OrInt16(addr *int16, a0 int16)

func OrUint16(addr *uint16, a0 uint16)

func OrInt32(addr *int32, a0 int32)

func OrUint32(addr *uint32, a0 uint32)

func OrInt64(addr *int64, a0 int64)

func OrUint64(addr *uint64, a0 uint64)

func OrInt(addr *int, a0 int)

func OrUint(addr *uint, a0 uint)

func OrUintptr(addr *uintptr, a0 uintptr)

func SubtractWithBorrowInt8(addr *int8, a0 int8)

func SubtractWithBorrowUint8(addr *uint8, a0 uint8)

func SubtractWithBorrowInt16(addr *int16, a0 int16)

func SubtractWithBorrowUint16(addr *uint16, a0 uint16)

func SubtractWithBorrowInt32(addr *int32, a0 int32)

func SubtractWithBorrowUint32(addr *uint32, a0 uint32)

func SubtractWithBorrowInt64(addr *int64, a0 int64)

func SubtractWithBorrowUint64(addr *uint64, a0 uint64)

func SubtractWithBorrowInt(addr *int, a0 int)

func SubtractWithBorrowUint(addr *uint, a0 uint)

func SubtractWithBorrowUintptr(addr *uintptr, a0 uintptr)

func SubtractInt8(addr *int8, a0 int8)

func SubtractUint8(addr *uint8, a0 uint8)

func SubtractInt16(addr *int16, a0 int16)

func SubtractUint16(addr *uint16, a0 uint16)

func SubtractInt32(addr *int32, a0 int32)

func SubtractUint32(addr *uint32, a0 uint32)

func SubtractInt64(addr *int64, a0 int64)

func SubtractUint64(addr *uint64, a0 uint64)

func SubtractInt(addr *int, a0 int)

func SubtractUint(addr *uint, a0 uint)

func SubtractUintptr(addr *uintptr, a0 uintptr)

func XorInt8(addr *int8, a0 int8)

func XorUint8(addr *uint8, a0 uint8)

func XorInt16(addr *int16, a0 int16)

func XorUint16(addr *uint16, a0 uint16)

func XorInt32(addr *int32, a0 int32)

func XorUint32(addr *uint32, a0 uint32)

func XorInt64(addr *int64, a0 int64)

func XorUint64(addr *uint64, a0 uint64)

func XorInt(addr *int, a0 int)

func XorUint(addr *uint, a0 uint)

func XorUintptr(addr *uintptr, a0 uintptr)

func XorAndCheckZeroInt8(addr *int8, a0 int8) int8

func XorAndCheckZeroUint8(addr *uint8, a0 uint8) uint8

func XorAndCheckZeroInt16(addr *int16, a0 int16) int16

func XorAndCheckZeroUint16(addr *uint16, a0 uint16) uint16

func XorAndCheckZeroInt32(addr *int32, a0 int32) int32

func XorAndCheckZeroUint32(addr *uint32, a0 uint32) uint32

func XorAndCheckZeroInt64(addr *int64, a0 int64) int64

func XorAndCheckZeroUint64(addr *uint64, a0 uint64) uint64

func XorAndCheckZeroInt(addr *int, a0 int) int

func XorAndCheckZeroUint(addr *uint, a0 uint) uint

func XorAndCheckZeroUintptr(addr *uintptr, a0 uintptr) uintptr

func AddAndSwapInt8(addr *int8, a0 int8) int8

func AddAndSwapUint8(addr *uint8, a0 uint8) uint8

func AddAndSwapInt16(addr *int16, a0 int16) int16

func AddAndSwapUint16(addr *uint16, a0 uint16) uint16

func AddAndSwapInt32(addr *int32, a0 int32) int32

func AddAndSwapUint32(addr *uint32, a0 uint32) uint32

func AddAndSwapInt64(addr *int64, a0 int64) int64

func AddAndSwapUint64(addr *uint64, a0 uint64) uint64

func AddAndSwapInt(addr *int, a0 int) int

func AddAndSwapUint(addr *uint, a0 uint) uint

func AddAndSwapUintptr(addr *uintptr, a0 uintptr) uintptr

func SwapInt8(addr *int8, a0 int8) int8

func SwapUint8(addr *uint8, a0 uint8) uint8

func SwapInt16(addr *int16, a0 int16) int16

func SwapUint16(addr *uint16, a0 uint16) uint16

func SwapInt32(addr *int32, a0 int32) int32

func SwapUint32(addr *uint32, a0 uint32) uint32

func SwapInt64(addr *int64, a0 int64) int64

func SwapUint64(addr *uint64, a0 uint64) uint64

func SwapInt(addr *int, a0 int) int

func SwapUint(addr *uint, a0 uint) uint

func SwapUintptr(addr *uintptr, a0 uintptr) uintptr
